### YamlMime:ManagedReference
items:
- uid: Ink.Platform.Settings
  commentId: N:Ink.Platform.Settings
  id: Ink.Platform.Settings
  children:
  - Ink.Platform.Settings.FileSettingsService
  - Ink.Platform.Settings.ISettingsService
  langs:
  - csharp
  - vb
  name: Ink.Platform.Settings
  nameWithType: Ink.Platform.Settings
  fullName: Ink.Platform.Settings
  type: Namespace
  assemblies:
  - Ink.Platform
references:
- uid: Ink.Platform.Settings.FileSettingsService
  commentId: T:Ink.Platform.Settings.FileSettingsService
  href: Ink.Platform.Settings.FileSettingsService.html
  name: FileSettingsService
  nameWithType: FileSettingsService
  fullName: Ink.Platform.Settings.FileSettingsService
- uid: Ink.Platform.Settings.ISettingsService
  commentId: T:Ink.Platform.Settings.ISettingsService
  parent: Ink.Platform.Settings
  href: Ink.Platform.Settings.ISettingsService.html
  name: ISettingsService
  nameWithType: ISettingsService
  fullName: Ink.Platform.Settings.ISettingsService
- uid: Ink.Platform.Settings
  commentId: N:Ink.Platform.Settings
  href: Ink.html
  name: Ink.Platform.Settings
  nameWithType: Ink.Platform.Settings
  fullName: Ink.Platform.Settings
  spec.csharp:
  - uid: Ink
    name: Ink
    href: Ink.html
  - name: .
  - uid: Ink.Platform
    name: Platform
    href: Ink.Platform.html
  - name: .
  - uid: Ink.Platform.Settings
    name: Settings
    href: Ink.Platform.Settings.html
  spec.vb:
  - uid: Ink
    name: Ink
    href: Ink.html
  - name: .
  - uid: Ink.Platform
    name: Platform
    href: Ink.Platform.html
  - name: .
  - uid: Ink.Platform.Settings
    name: Settings
    href: Ink.Platform.Settings.html
